apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - name: tempcont
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    volumeMounts:
    - name: testvol
      mountPath: /testvol
  volumes:
  - name: testvol
    persistentVolumeClaim:
      claimName: data 
